/*
 * Generated by Bluespec Compiler, version 2017.07.A (build 1da80f1, 2017-07-21)
 * 
 * On Fri Mar 16 17:07:03 IST 2018
 * 
 */
#include "bluesim_primitives.h"
#include "model_files.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_files::MODEL_files()
{
  files_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_files()
{
  MODEL_files *model = new MODEL_files();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_files &INST_top = *((MOD_files *)(instance_ptr));
	 INST_top.DEF_b__h171 = INST_top.INST_cnt.METH_read();
	 INST_top.DEF_CAN_FIRE_RL_dump = !primSLE8(1u, 32u, (tUInt32)(INST_top.DEF_b__h171), 32u, 0u);
	 INST_top.DEF_WILL_FIRE_RL_dump = INST_top.DEF_CAN_FIRE_RL_dump;
	 INST_top.DEF_CAN_FIRE_RL_ends = INST_top.INST_done.METH_read();
	 INST_top.DEF_WILL_FIRE_RL_ends = INST_top.DEF_CAN_FIRE_RL_ends;
	 INST_top.DEF_CAN_FIRE_RL_open = (INST_top.DEF_b__h171) == 0u;
	 INST_top.DEF_WILL_FIRE_RL_open = INST_top.DEF_CAN_FIRE_RL_open;
	 if (INST_top.DEF_WILL_FIRE_RL_ends)
	   INST_top.RL_ends();
	 if (INST_top.DEF_WILL_FIRE_RL_dump)
	   INST_top.RL_dump();
	 if (INST_top.DEF_WILL_FIRE_RL_open)
	   INST_top.RL_open();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_cnt.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fh.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_fmcd.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_done.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_files::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  files_instance = new MOD_files(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (files_instance->set_clk_0)("CLK");
}
void MODEL_files::destroy_model()
{
  delete files_instance;
  files_instance = NULL;
}
void MODEL_files::reset_model(bool asserted)
{
  (files_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_files::get_instance()
{
  return files_instance;
}

/* Fill in version numbers */
void MODEL_files::get_version(unsigned int *year,
			      unsigned int *month,
			      char const **annotation,
			      char const **build)
{
  *year = 2017u;
  *month = 7u;
  *annotation = "A";
  *build = "1da80f1";
}

/* Get the model creation time */
time_t MODEL_files::get_creation_time()
{
  
  /* Fri Mar 16 11:37:03 UTC 2018 */
  return 1521200223llu;
}

/* Control run-time licensing */
tUInt64 MODEL_files::skip_license_check()
{
  return 0llu;
}

/* State dumping function */
void MODEL_files::dump_state()
{
  (files_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_files & files_backing(tSimStateHdl simHdl)
{
  static MOD_files *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_files(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_files::dump_VCD_defs()
{
  (files_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_files::dump_VCD(tVCDDumpType dt)
{
  (files_instance->dump_VCD)(dt, vcd_depth(sim_hdl), files_backing(sim_hdl));
}
