/*
 * Generated by Bluespec Compiler, version 2017.07.A (build 1da80f1, 2017-07-21)
 * 
 * On Fri Mar 16 16:00:53 IST 2018
 * 
 */

/* Generation options: keep-fires */
#ifndef __files_h__
#define __files_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the files module */
class MOD_files : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_cnt;
  MOD_Reg<tUInt8> INST_done;
  MOD_Reg<tUInt32> INST_fh;
  MOD_Reg<tUInt32> INST_fmcd;
 
 /* Constructor */
 public:
  MOD_files(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_RL_ends;
  tUInt8 DEF_CAN_FIRE_RL_ends;
  tUInt8 DEF_WILL_FIRE_RL_dump;
  tUInt8 DEF_CAN_FIRE_RL_dump;
  tUInt8 DEF_WILL_FIRE_RL_open;
  tUInt8 DEF_CAN_FIRE_RL_open;
  tUInt32 DEF_b__h171;
 
 /* Local definitions */
 private:
  tUInt32 DEF_TASK_fopen___d3;
  tUInt32 DEF_fh___d7;
 
 /* Rules */
 public:
  void RL_open();
  void RL_dump();
  void RL_ends();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_files &backing);
  void vcd_defs(tVCDDumpType dt, MOD_files &backing);
  void vcd_prims(tVCDDumpType dt, MOD_files &backing);
};

#endif /* ifndef __files_h__ */
