/*
 * Generated by Bluespec Compiler, version 2017.07.A (build 1da80f1, 2017-07-21)
 * 
 * On Fri Mar 16 13:19:10 IST 2018
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkprog1.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkprog1::MODEL_mkprog1()
{
  mkprog1_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkprog1()
{
  MODEL_mkprog1 *model = new MODEL_mkprog1();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkprog1 &INST_top = *((MOD_mkprog1 *)(instance_ptr));
	 INST_top.DEF_CAN_FIRE_RL_rl_1 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_rl_1 = INST_top.DEF_CAN_FIRE_RL_rl_1;
	 if (INST_top.DEF_WILL_FIRE_RL_rl_1)
	   INST_top.RL_rl_1();
	 if (do_reset_ticks(simHdl))
	 {
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkprog1::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkprog1_instance = new MOD_mkprog1(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkprog1_instance->set_clk_0)("CLK");
}
void MODEL_mkprog1::destroy_model()
{
  delete mkprog1_instance;
  mkprog1_instance = NULL;
}
void MODEL_mkprog1::reset_model(bool asserted)
{
  (mkprog1_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkprog1::get_instance()
{
  return mkprog1_instance;
}

/* Fill in version numbers */
void MODEL_mkprog1::get_version(unsigned int *year,
				unsigned int *month,
				char const **annotation,
				char const **build)
{
  *year = 2017u;
  *month = 7u;
  *annotation = "A";
  *build = "1da80f1";
}

/* Get the model creation time */
time_t MODEL_mkprog1::get_creation_time()
{
  
  /* Fri Mar 16 07:49:10 UTC 2018 */
  return 1521186550llu;
}

/* Control run-time licensing */
tUInt64 MODEL_mkprog1::skip_license_check()
{
  return 0llu;
}

/* State dumping function */
void MODEL_mkprog1::dump_state()
{
  (mkprog1_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkprog1 & mkprog1_backing(tSimStateHdl simHdl)
{
  static MOD_mkprog1 *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkprog1(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkprog1::dump_VCD_defs()
{
  (mkprog1_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkprog1::dump_VCD(tVCDDumpType dt)
{
  (mkprog1_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkprog1_backing(sim_hdl));
}
